---
dependencies:
  - role: account_info
    tags: zone
galaxy_info:
  role_name: zone
  author: Taylor Kimball
  description: Manage cloudflare zones
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - zone
...
