---
allow_duplicates: true
dependencies:
  - role: accounts_info
    tags: rules_lists_info
galaxy_info:
  role_name: rules_lists_info
  author: Taylor Kimball
  description: Gather information about cloudflare rules lists
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - info
    - lists
    - rules
...
