---
zerotrust_connectivity_settings_account_id: null
zerotrust_connectivity_settings_api_token: null
zerotrust_connectivity_settings_icmp_proxy_enabled: false
zerotrust_connectivity_settings_offramp_warp_enabled: false
...
