---
dependencies:
  - role: accounts_info
    tags: cfd_tunnel
galaxy_info:
  role_name: cfd_tunnel
  author: Taylor Kimball
  description: Manage cloudflare cfd tunnels
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - tunnel
...
