---
dependencies:
  - role: account_info
    tags: access_service_token
galaxy_info:
  role_name: access_service_token
  author: Taylor Kimball
  description: Manage cloudflare access service tokens
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - access
    - cloudflare
    - service
    - token
...
