---
- name: Converge
  hosts: all
  roles:
    - role: zerotrust_connectivity_settings_info
      zerotrust_connectivity_settings_info_account_id: null
      zerotrust_connectivity_settings_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - zerotrust_connectivity_settings_info
...
