---
dependencies:
  - role: zone_info
    tags: page_rule
galaxy_info:
  role_name: page_rule
  author: Taylor Kimball
  description: Create and update cloudflare page rules
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - page
    - rule
...
