---
- name: Converge
  hosts: all
  roles:
    - role: access_apps_info
      access_apps_info_account_id: null
      access_apps_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - access_apps_info
...
