---
- name: Converge
  hosts: all
  roles:
    - role: zone_info
      tags:
        - molecule-idempotence-notest

    - role: zone_info
      zone_info_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
...
