---
- name: Verify
  hosts: all
  roles:
    - zone_info

  post_tasks:
    - name: Ensure cloudflare zone information is verified
      tags:
        - zone_info
      ansible.builtin.assert:
        that:
          - _zone_info_dict | length > 0
          - _zone_info_list | length > 0
...
