---
- name: Verify
  hosts: all
  roles:
    - role: zone_info
      zone_info_api_key: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"

  post_tasks:
    - name: Ensure cloudflare zone information is verified
      tags:
        - zone_info
      ansible.builtin.assert:
        that:
          - _zone_info_dict | length > 0
          - _zone_info_list | length > 0
...
