---
- name: Ensure cloudflare roles are executed
  hosts: cdn
  roles:
    - rules_lists
    - zones
    - rulesets
    - pagerules
    - pages_projects
    - access_service_tokens
    - access_groups
    - access_policies
    - access_apps
    - cfd_tunnel
    - devices_policy
    - devices_settings
    - zerotrust_connectivity_settings
    - warp_connector
    - dns
    - purge_cache
...
