---
dependencies:
  - role: accounts_info
    tags: pages_projects_info
galaxy_info:
  role_name: pages_projects_info
  author: Taylor Kimball
  description: Gather information about cloudflare pages projects
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - info
    - pages
    - projects
...
