---
allow_duplicates: true
galaxy_info:
  role_name: rulesets_info
  author: Taylor Kimball
  description: Gather information about cloudflare rulesets
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - info
    - rulesets
...
