---
dependencies:
  - role: zones_info
    tags: rulesets
galaxy_info:
  role_name: rulesets
  author: Taylor Kimball
  description: Manage cloudflare rulesets
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - rulesets
...
