---
- name: Ensure cloudflare access policies information is gathered
  tags:
    - access_policies
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ access_policies_api_token }}"
    method: GET
    status_code:
      - 200
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          access_policies_account_id ~
          '/access/policies' }}"
  register: __access_policies_query
  check_mode: false
  when:
    - access_policies_account_id is not none
    - access_policies_api_token is not none

- name: Ensure list of cloudflare access policies information is generated
  tags:
    - access_policies
  ansible.builtin.set_fact:
    __access_policies_list:
      "{{ __access_policies_query.json.result |
          d([]) }}"

- name: Ensure dict of cloudflare access policies information is generated
  tags:
    - access_policies
  ansible.builtin.set_fact:
    __access_policies_dict:
      "{{ (dict(__access_policies_list |
               json_query('[].name') |
               zip(__access_policies_list))) |
          d({}) }}"
...
