---
dependencies:
  - role: access_service_tokens_info
    tags: access_groups
galaxy_info:
  role_name: access_groups
  author: Taylor Kimball
  description: Manage cloudflare access groups
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - access
    - cloudflare
    - groups
...
