---
- name: Converge
  hosts: all
  roles:
    - role: devices_policy
      devices_policy_account_id: null
      devices_policy_api_token: null
      tags:
        - molecule-idempotence-notest

    - devices_policy
...
