---
- name: Converge
  hosts: all
  roles:
    - role: access_groups_info
      access_groups_info_account_id: null
      access_groups_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - access_groups_info
...
