---
access_service_tokens_account_id: "{{ _accounts_info_id }}"
access_service_tokens_api_token: "{{ cloudflare_api_token }}"

access_service_tokens_info_account_id: "{{ _accounts_info_id }}"
access_service_tokens_info_api_token: "{{ cloudflare_api_token }}"

access_service_tokens_list:
  - name: "{{ cloudflare_domain }}"
    duration: forever
...
