---
access_policies_account_id: "{{ _accounts_info_id }}"
access_policies_api_token: "{{ cloudflare_api_token }}"

access_policies_info_account_id: "{{ _accounts_info_id }}"
access_policies_info_api_token: "{{ cloudflare_api_token }}"

access_policies_list:
  - name: "{{ cloudflare_domain }}"
    decision: non_identity
    include:
      - group:
          id: "{{ _access_groups_info_dict[cloudflare_domain].id }}"
...
