---
cfd_tunnel_account_id: "{{ _accounts_info_id }}"
cfd_tunnel_api_token: "{{ cloudflare_api_token }}"

cfd_tunnel_info_account_id: "{{ _accounts_info_id }}"
cfd_tunnel_info_api_token: "{{ cloudflare_api_token }}"

cfd_tunnel_list:
  - name: "{{ cloudflare_domain }}-cfd"
    tunnel_secret: YjNhS3ZzQ0puNzNxdFljY0VmbkpGdWlOb3M3dWNxUlJ5YmhVUkx6S2NUNFBZN3k3bUZUb21McnUzd1BhTkh2aQo=
...
