---
devices_settings_account_id: "{{ _accounts_info_id }}"
devices_settings_api_token: "{{ accounts_info_api_token }}"

devices_settings_info_account_id: "{{ _accounts_info_id }}"
devices_settings_info_api_token: "{{ accounts_info_api_token }}"

devices_settings_gateway_proxy_enabled: true
devices_settings_gateway_udp_proxy_enabled: true
devices_settings_use_zt_virtual_ip: true
...
