---
rules_lists_account_id: "{{ _accounts_info_id }}"
rules_lists_api_token: "{{ cloudflare_api_token }}"

rules_lists_info_account_id: "{{ _accounts_info_id }}"
rules_lists_info_api_token: "{{ cloudflare_api_token }}"

rules_lists_list:
  - kind: ip
    name: uptime_robot
    elements:
      "{{ lookup('ansible.builtin.url',
                 'https://uptimerobot.com/inc/files/ips/IPv4.txt',
                 wantlist=true) |
          map('community.general.dict_kv', 'ip') |
          sort(attribute='ip') }}"
...
