---
zerotrust_connectivity_settings_account_id: "{{ _accounts_info_id }}"
zerotrust_connectivity_settings_api_token: "{{ accounts_info_api_token }}"

zerotrust_connectivity_settings_info_account_id: "{{ _accounts_info_id }}"
zerotrust_connectivity_settings_info_api_token: "{{ accounts_info_api_token }}"

zerotrust_connectivity_settings_icmp_proxy_enabled: true
zerotrust_connectivity_settings_offramp_warp_enabled: true
...
