---
zones_account_id: "{{ _accounts_info_id }}"
zones_api_token: "{{ cloudflare_api_token }}"

zones_info_account_id: "{{ _accounts_info_id }}"
zones_info_api_token: "{{ cloudflare_api_token }}"

zones_list:
  - name: "{{ cloudflare_domain }}"
    type: full
    settings:
      - id: automatic_https_rewrites
        value: 'on'
      - id: always_use_https
        value: 'on'
      - id: browser_check
        value: 'on'
      - id: challenge_ttl
        value: 1800
      - id: development_mode
        value: 'on'
      - id: email_obfuscation
        value: 'on'
      - id: hotlink_protection
        value: 'on'
      - id: ip_geolocation
        value: 'on'
      - id: ipv6
        value: 'off'
      - id: min_tls_version
        value: 1.3
      - id: opportunistic_encryption
        value: 'on'
      - id: opportunistic_onion
        value: 'on'
      - id: pseudo_ipv4
        value: 'off'
      - id: security_level
        value: high
      - id: server_side_exclude
        value: 'on'
      - id: ssl
        value: strict
      - id: websockets
        value: 'on'
...
