---
- name: Verify
  hosts: all
  roles:
    - warp_connector_info

  post_tasks:
    - name: Ensure cloudflare warp connector information is verified
      tags:
        - warp_connector_info
      ansible.builtin.assert:
        that:
          - _warp_connector_info_dict | length > 0
          - _warp_connector_info_list | length > 0
...
