---
- name: Converge
  hosts: all
  roles:
    - role: accounts_info
      accounts_info_api_token: null
      accounts_info_name: null
      tags:
        - molecule-idempotence-notest

    - accounts_info
...
