---
allow_duplicates: true
dependencies:
  - role: accounts_info
    tags: rule_list_info
galaxy_info:
  role_name: rule_list_info
  author: Taylor Kimball
  description: Gather information about cloudflare rule lists
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - info
    - list
    - rule
...
