---
- name: Converge
  hosts: all
  roles:
    - role: pages_project_info
      pages_project_info_account_id: null
      pages_project_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - pages_project_info
...
