---
- name: Verify
  hosts: all
  roles:
    - pages_project_info

  post_tasks:
    - name: Ensure cloudflare pages project information is verified
      tags:
        - pages_project_info
      ansible.builtin.assert:
        that:
          - _pages_project_info_dict | length > 0
          - _pages_project_info_list | length > 0
...
