---
dependencies:
  - role: zone_info
    tags: ruleset_entrypoint
galaxy_info:
  role_name: ruleset_entrypoint
  author: Taylor Kimball
  description: Create and update cloudflare entrypoint rule sets
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - entry
    - point
    - rule
    - set
...
