---
- name: Converge
  hosts: all
  roles:
    - role: access_app
      access_app_list: []
      tags:
        - molecule-idempotence-notest

    - role: access_service_token
      tags:
        - molecule-idempotence-notest

    - role: access_group
      tags:
        - molecule-idempotence-notest

    - role: access_policy
      tags:
        - molecule-idempotence-notest

    - access_app
...
