---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        account_info_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
        account_info_name: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_NAME') }}"

        access_app_account_id: "{{ _account_info_id }}"
        access_app_api_token: "{{ account_info_api_token }}"
        access_app_list:
          - domain: taylorkimball.org
            name: taylorkimball.org
            type: self_hosted

        zone_account_id: "{{ _account_info_id }}"
        zone_api_token: "{{ account_info_api_token }}"
        zone_list:
          - name: taylorkimball.org
            type: full

verifier:
  name: ansible
  options:
    diff: true
...
