---
allow_duplicates: true
dependencies:
  - role: accounts_info
    tags: access_apps_info
galaxy_info:
  role_name: access_apps_info
  author: Taylor Kimball
  description: Gather information about cloudflare access apps
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - access
    - apps
    - cloudflare
    - info
...
