---
dependencies:
  - role: zone_info
    tags: scrape_shield
galaxy_info:
  role_name: scrape_shield
  author: Taylor Kimball
  description: Manage cloudflare scrape shield settings
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - scrape
    - shield
...
