---
- name: Verify
  hosts: all

  pre_tasks:
    - name: Ensure inventory lists are formatted
      tags:
        - zones
      ansible.builtin.set_fact:
        zones_list:
          "{{ zones_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - zones
...
