---
- name: Converge
  hosts: all
  roles:
    - role: access_group
      access_group_account_id: null
      access_group_api_token: null
      tags:
        - molecule-idempotence-notest

    - role: access_service_token
      tags:
        - molecule-idempotence-notest

    - access_group
...
