---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        accounts_info_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
        accounts_info_name: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_NAME') }}"

        access_group_account_id: "{{ _accounts_info_id }}"
        access_group_api_token: "{{ accounts_info_api_token }}"
        access_group_list:
          - name: taylorkimball.org
            include:
              - service_token:
                  token_id: "{{ _access_service_token_info_dict['taylorkimball.org'].id }}"
            is_default: false

        access_service_token_account_id: "{{ _accounts_info_id }}"
        access_service_token_api_token: "{{ accounts_info_api_token }}"
        access_service_token_info_account_id: "{{ _accounts_info_id }}"
        access_service_token_info_api_token: "{{ accounts_info_api_token }}"
        access_service_token_list:
          - name: taylorkimball.org
            duration: forever

verifier:
  name: ansible
  options:
    diff: true
...
