---
dependencies:
  - role: zones_info
    tags: purge_cache
galaxy_info:
  role_name: purge_cache
  author: Taylor Kimball
  description: Manage cloudflare purging of cache
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cache
    - cloudflare
    - purge
...
