---
- name: Converge
  hosts: all
  roles:
    - role: access_service_token
      access_service_token_account_id: null
      access_service_token_api_token: null
      tags:
        - molecule-idempotence-notest

    - access_service_token
...
