---
dependencies:
  - role: account_info
    tags: access_app
galaxy_info:
  role_name: application
  author: Taylor Kimball
  description: Create and update cloudflare access apps
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - access
    - app
    - cloudflare
...
