---
- name: Ensure cloudflare cfd tunnels information tasks are included
  tags:
    - cfd_tunnel
  ansible.builtin.include_tasks:
    apply:
      tags:
        - cfd_tunnel
    file: info.yml

- name: Ensure cloudflare cfd tunnels are present
  tags:
    - cfd_tunnel
  ansible.builtin.uri:
    body:
      config_src: "{{ _post.config_src | d('local') }}"
      name: "{{ _post.name }}"
      tunnel_secret: "{{ _post.tunnel_secret | trim }}"
    body_format: json
    headers:
      Authorization: "Bearer {{ cfd_tunnel_api_token }}"
    method: POST
    status_code:
      - 200
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          cfd_tunnel_account_id ~
          '/cfd_tunnel' }}"
  loop: "{{ cfd_tunnel_list }}"
  loop_control:
    label: "{{ _post.name | d(none) }}"
    loop_var: _post
  changed_when: true
  when:
    - cfd_tunnel_account_id is not none
    - cfd_tunnel_api_token is not none
    - _post.name is defined
    - _post.name not in __cfd_tunnel_dict.keys()
    - _post.state is not defined or
      _post.state == 'present'
    - _post.tunnel_secret is defined

- name: Ensure cloudflare cfd tunnels information tasks are included
  tags:
    - cfd_tunnel
  ansible.builtin.include_tasks:
    apply:
      tags:
        - cfd_tunnel
    file: info.yml

- name: Ensure cloudflare cfd tunnels are updated
  tags:
    - cfd_tunnel
  ansible.builtin.uri:
    body:
      name: "{{ _patch.name }}"
      tunnel_secret: "{{ _patch.tunnel_secret | trim }}"
    body_format: json
    headers:
      Authorization: "Bearer {{ cfd_tunnel_api_token }}"
    method: PATCH
    status_code:
      - 200
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          cfd_tunnel_account_id ~
          '/cfd_tunnel/' ~
          __cfd_tunnel_dict[_patch.name].id }}"
  loop: "{{ cfd_tunnel_list }}"
  loop_control:
    label: "{{ _patch.name | d(none) }}"
    loop_var: _patch
  changed_when: true
  when:
    - cfd_tunnel_account_id is not none
    - cfd_tunnel_api_token is not none
    - _patch.name is defined
    - _patch.name in __cfd_tunnel_dict.keys()
    - _patch.state is not defined or
      _patch.state == 'present'
    - _patch.tunnel_secret is defined
    - __cfd_tunnel_dict[_patch.name].id is defined

- name: Ensure cloudflare cfd tunnels are absent
  tags:
    - cfd_tunnel
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ cfd_tunnel_api_token }}"
    method: DELETE
    status_code:
      - 200
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          cfd_tunnel_account_id ~
          '/cfd_tunnel/' ~
          __cfd_tunnel_dict[_delete.name].id }}"
  loop: "{{ cfd_tunnel_list }}"
  loop_control:
    label: "{{ _delete.name | d(none) }}"
    loop_var: _delete
  changed_when: true
  when:
    - cfd_tunnel_account_id is not none
    - cfd_tunnel_api_token is not none
    - _delete.name is defined
    - _delete.name in __cfd_tunnel_dict.keys()
    - _delete.state is defined and
      _delete.state == 'absent'
    - __cfd_tunnel_dict[_delete.name].id is defined
...
