---
allow_duplicates: true
dependencies: []
galaxy_info:
  role_name: account_info
  author: Taylor Kimball
  description: Gather information about cloudflare account
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - account
    - cloudflare
    - info
...
