---
dependencies:
  - role: accounts_info
    tags: devices_policy_info
galaxy_info:
  role_name: devices_policy_info
  author: Taylor Kimball
  description: Gather information about cloudflare devices policy
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - devices
    - info
    - policy
...
