---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        accounts_info_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
        accounts_info_name: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_NAME') }}"
        cfd_tunnel_info_account_id: "{{ _accounts_info_id }}"
        cfd_tunnel_info_api_token: "{{ accounts_info_api_token }}"
        zones_info_api_token: "{{ accounts_info_api_token }}"

        dns_api_token: "{{ accounts_info_api_token }}"
        dns_records:
          - zone: linuxhq.dev
            records:
              - record: one
                proxied: true
                type: A
                value: 8.8.8.1
              - record: two
                proxied: false
                type: A
                value: 8.8.8.2
              - record: three
                proxied: true
                type: A
                value: 8.8.8.3
              - record: four
                proxied: false
                type: A
                value: 8.8.8.4
              - record: five
                proxied: true
                type: A
                value: 8.8.8.5
              - record: six
                proxied: false
                type: A
                value: 8.8.8.6
              - record: seven
                proxied: true
                type: A
                value: 8.8.8.7
              - record: eight
                proxied: false
                type: A
                value: 8.8.8.8
              - record: nine
                proxied: true
                type: A
                value: 8.8.8.9
              - record: ten
                proxied: false
                type: A
                value: 8.8.8.10
              - record: eleven
                proxied: true
                type: A
                value: 8.8.8.11
              - record: twelve
                proxied: false
                type: A
                value: 8.8.8.12
              - record: thirteen
                proxied: true
                type: A
                value: 8.8.8.13

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - converge
    - check
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
