---
- name: Verify
  hosts: all

  pre_tasks:
    - name: Ensure inventory lists are formatted
      tags:
        - dns
      ansible.builtin.set_fact:
        dns_records:
          - zone: taylorkimball.org
            records:
              "{{ dns_records[0].records |
                  map('combine', {'state': 'absent'}) |
                  list }}"

  roles:
    - dns
...
