---
- name: Verify
  hosts: all

  pre_tasks:
    - name: Ensure inventory lists are formatted
      tags:
        - dns
      ansible.builtin.set_fact:
        dns_records:
          - zone: lhqcfv2.net
            records:
              "{{ dns_records[0].records |
                  map('combine', {'state': 'absent'}) |
                  list }}"
        zone_list:
          "{{ zone_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - dns
    - zone
...
