---
dependencies:
  - role: account_info
    tags: pages_project
galaxy_info:
  role_name: pages_project
  author: Taylor Kimball
  description: Create and update cloudflare pages projects
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - pages
    - project
...
