---
allow_duplicates: true
dependencies:
  - role: account_info
    tags: access_app_info
galaxy_info:
  role_name: access_app_info
  author: Taylor Kimball
  description: Gather information about cloudflare access applications
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - access
    - app
    - cloudflare
    - info
...
