---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        accounts_info_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"
        accounts_info_name: "{{ lookup('env', 'CLOUDFLARE_ACCOUNT_NAME') }}"

        access_apps_account_id: "{{ _accounts_info_id }}"
        access_apps_api_token: "{{ accounts_info_api_token }}"
        access_apps_list:
          - name: linuxhq.dev
            domain: linuxhq.dev
            destinations:
              - type: public
                uri: linuxhq.dev
              - type: public
                uri: secondary.linuxhq.dev
            policies:
              - id: "{{ _access_policies_info_dict['linuxhq.dev'].id }}"
            type: self_hosted

        access_groups_account_id: "{{ _accounts_info_id }}"
        access_groups_api_token: "{{ accounts_info_api_token }}"
        access_groups_info_account_id: "{{ _accounts_info_id }}"
        access_groups_info_api_token: "{{ accounts_info_api_token }}"
        access_groups_list:
          - name: linuxhq.dev
            include:
              - service_token:
                  token_id: "{{ _access_service_tokens_info_dict['linuxhq.dev'].id }}"
            is_default: false

        access_policies_account_id: "{{ _accounts_info_id }}"
        access_policies_api_token: "{{ accounts_info_api_token }}"
        access_policies_info_account_id: "{{ _accounts_info_id }}"
        access_policies_info_api_token: "{{ accounts_info_api_token }}"
        access_policies_list:
          - name: linuxhq.dev
            decision: non_identity
            include:
              - group:
                  id: "{{ _access_groups_info_dict['linuxhq.dev'].id }}"

        access_service_tokens_account_id: "{{ _accounts_info_id }}"
        access_service_tokens_api_token: "{{ accounts_info_api_token }}"
        access_service_tokens_info_account_id: "{{ _accounts_info_id }}"
        access_service_tokens_info_api_token: "{{ accounts_info_api_token }}"
        access_service_tokens_list:
          - name: linuxhq.dev
            duration: forever

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - converge
    - check
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
