---
- name: Converge
  hosts: all
  roles:
    - role: access_app_info
      access_app_info_account_id: null
      access_app_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - access_app_info
...
