---
- name: Converge
  hosts: all
  roles:
    - role: tunnel_info
      tunnel_info_account_id: null
      tunnel_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - tunnel_info
...
