---
- name: Verify
  hosts: all
  roles:
    - cfd_tunnel_info

  post_tasks:
    - name: Ensure cloudflare cfd tunnel information is verified
      tags:
        - cfd_tunnel_info
      ansible.builtin.assert:
        that:
          - _cfd_tunnel_info_dict | length > 0
          - _cfd_tunnel_info_list | length > 0
...
