---
- name: Verify
  hosts: all

  pre_tasks:
    - name: Ensure inventory lists are formatted
      tags:
        - pages_project
      ansible.builtin.set_fact:
        pages_project_list:
          "{{ pages_project_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - pages_project
...
