---
- name: Converge
  hosts: all
  roles:
    - role: access_service_token_info
      access_service_token_info_account_id: null
      access_service_token_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - access_service_token_info
...
