---
- name: Verify
  hosts: all
  roles:
    - access_service_token_info

  post_tasks:
    - name: Ensure cloudflare access service token information is verified
      tags:
        - access_service_token_info
      ansible.builtin.assert:
        that:
          - _access_service_token_info_dict | length > 0
          - _access_service_token_info_list | length > 0
...
