---
dependencies:
  - role: access_policies_info
    tags: access_apps
galaxy_info:
  role_name: access_apps
  author: Taylor Kimball
  description: Manage cloudflare access apps
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - access
    - apps
    - cloudflare
...
