---
- name: Ensure cloudflare access groups information is gathered
  tags:
    - access_groups
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ access_groups_api_token }}"
    method: GET
    status_code:
      - 200
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          access_groups_account_id ~
          '/access/groups' }}"
  register: __access_groups_query
  check_mode: false
  when:
    - access_groups_account_id is not none
    - access_groups_api_token is not none

- name: Ensure list of cloudflare access groups information is generated
  tags:
    - access_groups
  ansible.builtin.set_fact:
    __access_groups_list:
      "{{ __access_groups_query.json.result |
          d([]) }}"

- name: Ensure dict of cloudflare access groups information is generated
  tags:
    - access_groups
  ansible.builtin.set_fact:
    __access_groups_dict:
      "{{ (dict(__access_groups_list |
               json_query('[].name') |
               zip(__access_groups_list))) |
          d({}) }}"
...
