---
- name: Ensure cloudflare access groups information tasks are included
  tags:
    - access_groups
  ansible.builtin.include_tasks:
    apply:
      tags:
        - access_groups
    file: info.yml

- name: Ensure cloudflare access groups are present
  tags:
    - access_groups
  ansible.builtin.uri:
    body:
      exclude: "{{ _post.exclude | d(omit) }}"
      include: "{{ _post.include }}"
      is_default: "{{ _post.is_default | d(false) }}"
      name: "{{ _post.name }}"
      require: "{{ _post.require | d(omit) }}"
    body_format: json
    headers:
      Authorization: "Bearer {{ access_groups_api_token }}"
    method: POST
    status_code:
      - 201
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          access_groups_account_id ~
          '/access/groups' }}"
  loop: "{{ access_groups_list }}"
  loop_control:
    label: "{{ _post.name | d(none) }}"
    loop_var: _post
  changed_when: true
  when:
    - access_groups_account_id is not none
    - access_groups_api_token is not none
    - _post.include is defined
    - _post.name is defined
    - _post.name not in __access_groups_dict.keys()
    - _post.state is not defined or
      _post.state == 'present'

- name: Ensure cloudflare access groups information tasks are included
  tags:
    - access_groups
  ansible.builtin.include_tasks:
    apply:
      tags:
        - access_groups
    file: info.yml

- name: Ensure cloudflare access groups are updated
  tags:
    - access_groups
  ansible.builtin.uri:
    body:
      exclude: "{{ _put.exclude | d(omit) }}"
      include: "{{ _put.include }}"
      is_default: "{{ _put.is_default | d(false) }}"
      name: "{{ _put.name }}"
      require: "{{ _put.require | d(omit) }}"
    body_format: json
    headers:
      Authorization: "Bearer {{ access_groups_api_token }}"
    method: PUT
    status_code:
      - 200
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          access_groups_account_id ~
          '/access/groups/' ~
          __access_groups_dict[_put.name].id }}"
  loop: "{{ access_groups_list }}"
  loop_control:
    label: "{{ _put.name | d(none) }}"
    loop_var: _put
  changed_when: true
  when:
    - access_groups_account_id is not none
    - access_groups_api_token is not none
    - _put.include is defined
    - _put.name is defined
    - _put.name in __access_groups_dict.keys()
    - _put.state is not defined or
      _put.state == 'present'
    - __access_groups_dict[_put.name] is defined
    - __access_groups_dict[_put.name].id is defined

- name: Ensure cloudflare access groups are absent
  tags:
    - access_groups
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ access_groups_api_token }}"
    method: DELETE
    status_code:
      - 200
      - 202
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          access_groups_account_id ~
          '/access/groups/' ~
          __access_groups_dict[_delete.name].id }}"
  loop: "{{ access_groups_list }}"
  loop_control:
    label: "{{ _delete.name | d(none) }}"
    loop_var: _delete
  changed_when: true
  when:
    - access_groups_account_id is not none
    - access_groups_api_token is not none
    - _delete.name is defined
    - _delete.name in __access_groups_dict.keys()
    - _delete.state is defined and
      _delete.state == 'absent'
    - __access_groups_dict[_delete.name] is defined
    - __access_groups_dict[_delete.name].id is defined
...
