---
- name: Converge
  hosts: all
  roles:
    - role: access_groups
      access_groups_list: []
      tags:
        - molecule-idempotence-notest

    - role: access_service_tokens
      tags:
        - molecule-idempotence-notest

    - access_groups
...
