---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        zones_info_api_token: "{{ lookup('env', 'CLOUDFLARE_API_TOKEN') }}"

        pagerules_api_token: "{{ zones_info_api_token }}"
        pagerules_list:
          - zone_id: "{{ _zones_info_dict['taylorkimball.org'].id }}"
            pagerules:
              - actions:
                  - id: forwarding_url
                    value:
                      status_code: 301
                      url: https://github.com/tkimball83
                status: active
                targets:
                  - constraint:
                      operator: matches
                      value: "taylorkimball.org/*"
                    target: url
              - actions:
                  - id: forwarding_url
                    value:
                      status_code: 301
                      url: https://github.com/tkimball83
                status: active
                targets:
                  - constraint:
                      operator: matches
                      value: "www.taylorkimball.org/*"
                    target: url

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - converge
    - check
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
