---
- name: Converge
  hosts: all
  roles:
    - role: access_policies
      access_policies_account_id: null
      access_policies_api_token: null
      tags:
        - molecule-idempotence-notest

    - role: access_service_tokens
      tags:
        - molecule-idempotence-notest

    - role: access_group
      tags:
        - molecule-idempotence-notest

    - access_policies
...
