---
dependencies:
  - role: accounts_info
    tags: zerotrust_connectivity_settings
galaxy_info:
  role_name: zerotrust_connectivity_settings
  author: Taylor Kimball
  description: Manage cloudflare zerotrust connectivity settings
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - connectivity
    - settings
    - zerotrust
...
