---
- name: Ensure cloudflare access policy information is gathered
  tags:
    - access_policy_info
  ansible.builtin.uri:
    headers:
      Authorization: "Bearer {{ access_policy_info_api_token }}"
    method: GET
    status_code:
      - 200
    url:
      "{{ 'https://api.cloudflare.com/client/v4/accounts/' ~
          access_policy_info_account_id ~
          '/access/policies' }}"
  register: __access_policy_info_query
  when:
    - access_policy_info_account_id is not none
    - access_policy_info_api_token is not none

- name: Ensure list of cloudflare access policy information is generated
  tags:
    - access_policy_info
  ansible.builtin.set_fact:
    _access_policy_info_list:
      "{{ __access_policy_info_query.json.result |
          d([]) }}"

- name: Ensure dict of cloudflare access policy information is generated
  tags:
    - access_policy_info
  ansible.builtin.set_fact:
    _access_policy_info_dict:
      "{{ (dict(_access_policy_info_list |
               json_query('[].name') |
               zip(_access_policy_info_list))) |
          d({}) }}"
...
