---
- name: Converge
  hosts: all
  roles:
    - role: access_group_info
      access_group_info_account_id: null
      access_group_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - access_group_info
...
