---
- name: Verify
  hosts: all
  roles:
    - access_group_info

  post_tasks:
    - name: Ensure cloudflare access group information is verified
      tags:
        - access_group_info
      ansible.builtin.assert:
        that:
          - _access_group_info_dict | length > 0
          - _access_group_info_list | length > 0
...
