---
dependencies:
  - role: access_group_info
    tags: access_policy
galaxy_info:
  role_name: access_policy
  author: Taylor Kimball
  description: Manage cloudflare access policies
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - access
    - cloudflare
    - policy
...
