---
dependencies:
  - role: cfd_tunnel_info
    tags: dns
  - role: warp_connector_info
    tags: dns
galaxy_info:
  role_name: dns
  author: Taylor Kimball
  description: Manage cloudflare dns records
  license: GPL-3.0-or-later
  min_ansible_version: 2.15.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - cloudflare
    - dns
...
