---
- name: Verify
  hosts: all

  pre_tasks:
    - name: Ensure inventory lists are formatted
      tags:
        - rules_lists
      ansible.builtin.set_fact:
        rules_lists_list:
          "{{ rules_lists_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - rules_lists
...
