---
- name: Verify
  hosts: all

  pre_tasks:
    - name: Ensure inventory lists are formatted
      tags:
        - pages_projects
      ansible.builtin.set_fact:
        pages_projects_list:
          "{{ pages_projects_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - pages_projects
...
