---
- name: Converge
  hosts: all
  roles:
    - role: access_policy_info
      access_policy_info_account_id: null
      access_policy_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - access_policy_info
...
