---
- name: Verify
  hosts: all
  roles:
    - access_policy_info

  post_tasks:
    - name: Ensure cloudflare access policy information is verified
      tags:
        - access_policy_info
      ansible.builtin.assert:
        that:
          - _access_policy_info_dict | length > 0
          - _access_policy_info_list | length > 0
...
