---
- name: Converge
  hosts: all
  roles:
    - role: pages_projects_info
      pages_projects_info_account_id: null
      pages_projects_info_api_token: null
      tags:
        - molecule-idempotence-notest

    - pages_projects_info
...
